server:
  port: ${SERVER_PORT:8337}

spring:
  application:
    name: noveo-test-assignment


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/noveo
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop


app:
  productsToInit:
    - name: "Iphone"
      price: 100f
    - name: "Наушники"
      price: 20.0f
    - name: "Чехол"
      price: 10.0f
  couponsToInit:
    - code: "D10"
      discount: 10.0f
    - code: "D20"
      discount: 20.0f
    - code: "P10"
      discount: 20.0f
    - code: "P100"
      discount: 100.0f
  taxesToInit:
    - countryCode: "DE"
      taxPercent: 19.0f
    - countryCode: "IT"
      taxPercent: 22.0f
    - countryCode: "GR"
      taxPercent: 24.0f
    - countryCode: "FR"
      taxPercent: 20.0f