server:
  port: ${SERVER_PORT:8337}
  error:
    include-message: always
    include-binding-errors: always

spring:
  application:
    name: noveo-test-assignment


  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/noveo
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:username}
    password: ${POSTGRES_PASSWORD:password}

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop


app:
  productsToInit:
    - name: "Iphone"
      price: 100.0
    - name: "Наушники"
      price: 20.0
    - name: "Чехол"
      price: 10.0
    - name: " Patek Philippe Grandmaster Chime"
      price: 31194000.0
  couponsToInit:
    - code: "D15"
      discount: 15.0f
      coupon-type: D
    - code: "D40"
      discount: 40.0f
      coupon-type: D
    - code: "P10"
      discount: 20.0f
      coupon-type: P
    - code: "P100"
      discount: 100.0f
      coupon-type: P
  taxesToInit:
    - taxPercent: 19.0f
      regex-pattern: "^DE\\d{9}$"
    - taxPercent: 22.0f
      regex-pattern: "^IT\\d{11}$"
    - taxPercent: 24.0f
      regex-pattern: "^GR\\d{9}$"
    - taxPercent: 20.0f
      regex-pattern: "^FR[A-Z]{2}\\d{9}$"